language: php
php: 5.3

source_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdWxQL0cwejVZb2FBOGdpWVZucTByVlg4TWpwWW9zbXBlN04zOE1YWHE3UzFjNDVqCkE1VnVIUFV2LzFkVXl6K2xZUmpWd3hVYlJEMEhmcVBEM1AwMWc3dEJOR3N4M1FLUUxBbEk1anBNV3QzVHI5cEMKVlcwZ1JocjhRQTdtVExEM0NkOUQya1YwWS9Qa2xMNjJXeWE4bTdlL280Tjl6R0ROOUdFOFhmTnNsU3FXbzNzSgp5bDZwdU12emJCWHhxOFd1Tm5CRTNQZ0Q2dWRNblN4cGphc0xNOW5BR3JlZlJHaEF1YjJYWE9lUmlYL21VRWhZClVMUGFud3dVVnhUMmpjOTA1Tno2UHBXaEVrQVcyaCtVSEIwdURCQkt2Y0Z1cTFmRHQzb3VKSGNsRmU5R20weXYKRmtRbkNBOUpsdnpILzFwWUN5VzNUSElMdlBOYUNoTlpwYVBFeVFJREFRQUJBb0lCQUh6QlVNV092RXRqazJKNgpyc1Q0VTVEYlNZaTMyRERtcFR2VjVqQ254c2VJcnhVMytNT2xnWnlSN2hrZzkvMCtHQlR5OCsweWJKYzc1WkM5ClJaN3BTck53NVMrYnRqOHNRQ3U3Njd0NnZUVDU0WXFVc0dWU001Rzg3N2hVUVk2SHptQWx4T0NZTUYzY0p1Z1EKNlRnT3I2bnpWYlM5amJVUis5UHNadWJnM1lyaFcwR01uVHA0blBzM3RzbmhUWXRaeDE3eUdtc3k4TGNUQVcxMgptNjRYUEwxSVY5YU1vdVhiNzlpcmY4ZFJYcTVCVjZJckJMbW84R3Y1aFRLUE1DcGNsSmhKNFNENWpoTFBvREFZCmk1anBUTGczSDNIL2prV3VXWVdZeDNPYjZraGYzN28rSEZuRGhmai9DWStnS3hLS0JIbEpVUDBVVGorbUxoek4KcHowUHFBRUNnWUVBOEN0UVF2cy9xY0t2MTBSZU5MTFJMTkxLYyttWSt3RWVGWDJiRDVyQ2tFN0o0MWVwVXl4bQpRRkNlVFFmR1EvMi9HYmplSWtWOVphQzIvYjRVNHQ2OGZzTldPWTJOYnU3Nkh5WmExWTYxVSt3Y1hJNFNOU0RLCnJFY29EUnFVR09FQTFUVVhYbU5tSzZiUmIyaU1SVW04cXBYZ0NwMisrZWM1d1dKVVI5TnBpcUVDZ1lFQXhwd24KRE1iZlkxb2FJMVZjOW9vY2ZQTjhDVUQwN01IL3hkaUlHbjVCZytCUmdFTlZSeTIzcWxHNE8velJqUVhsUTA1egpMY0ZqMjRFODg1MndUQm9wQ3pMWjBta1grZzd2K3BqNVhxR2lFUml5TjVpUVgxeTgrNEZqdmUxQndreDlFd085CnkyYnVhWXcrb1h0WW1UQ2Rsd2t3NUZOZ2NJTEMvWmRMcThkYjhTa0NnWUVBMExvRUJrS1BvTDBYejNHV29od3EKbU5jVnBrbUZiOWdYeWp1Z2tKNUNxK0lkcVp4ZEIzRVY2SjFvQnJCVUNuRTBMV215Zkh5Q0w5bk9UNVpzVm9PWAp0RitWeDIwVFZ5OFFhQlFRYTN1Y2NiUkpMZE0zVmI4TEJWRE9LUjFKU3BuNS9GSW8zaHByQ0ZMeHYrNVB3a1FFCldRanFicStMODJxV2tsQWZ5VkNlY0NFQ2dZQWwrbTR0TDBwQVFWYUdNeWlYckVsT1MzRUlnL2RSM3JiK0tpMjgKZ3pBYis2VWFGY1lVMmxVb3FIL0dXTTNwWFpzOWg1N1d2UWhQVFNOT29uUzMyTGpJZjJ6UG8zRUdUQnp2bXBqMAowNHVlSVU3UytzV0F0c2NjZ04yRnoveW5IdUU3NVpkQmNlbGRIWWhNY0wyOGJXTjFJampMTUhaY2pXU2tBVzVpCjVyaGFJUUtCZ1FEakNDcWIxUXptRGMraSttamhEdWlDei83VTZGbUhIckIrcHlGMFVJYzUyS3htNU9ZbWI3Q0UKNndxT2FOUTcvV2ZlbFBJMnkxc3JVdTB1MzhzbFN6Y1R0KzNLWEEzdUdKWi9KWWJIMzhIZEY5V0xOR3JhMk5SZwozcXEzTjhMeUVBWjdndndxYXc0SFI1MGZLMVFnT2h4QXZ1OFRoODk3MWw4WXJwcTNITS9HQ1E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
env:
  global: 
    - PNAME='openberkeley-drops'
    - PSITE='openberkeley-drops'
    - PUUID='7a2c33ae-1103-558e-bb6b-b9a40a7e3786'
    - PSOURCE='dev'

    # The authentication details for a Pantheon account with access to the site
#    - secure: "aFHFuNedOqpT5uKtsMsALj4eNm8FkPruzEmgiKEMAeVzx/52LxqBFAQ4zWx+X8j4ormhZBV/HyBqoLa7u7KFBmAiVo2Sq7KrDnwqRdEbfl/51zO2BTkUAbGkFkG52iYK4CM6x8KfG39JVKVjaLrrFe6xeifbhnkcvpqOV/LZzKg="
 #   - secure: "VFTOWaep7xho34hTxMRzB4tLyWGYWe3lMdnsnp014WLomsae20eWR3bHLuK+G3rEdGCNSr+6msuYJxvi0nhsTf+Mvn+XNBIAl6JjCXOPw5+rVMSXHFzVvL3vkd6yLRiQyrVV9UyvTnaiAXS8mS9galG33wnL4GskHjsWm5kBuaU="

    - PEMAIL='ist-drupal@lists.berkeley.edu'
    - PPASS='test'

    # The host against which the build will be run
    - PHOST="https://$TRAVIS_BRANCH-$PNAME.pantheon.berkeley.edu"

install:
  # Ensure the build doesn't get hung up on adding unknown hosts.
  - echo "StrictHostKeyChecking no" > ~/.ssh/config

  # Install drush.
  - composer global require drush/drush:6.2.0
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Install terminus.
  - git clone https://github.com/pantheon-systems/terminus.git $HOME/.drush/terminus
  - cd $HOME/.drush/terminus
  - composer update --no-dev
  - drush cc drush

before_script:
# Authenticate with Pantheon via Terminus.
- drush pauth $PEMAIL --password=$PPASS

# Add Pantheon as a remote to our repo and force push to it.
- cd $TRAVIS_BUILD_DIR
- git checkout -b $PSITE
- git remote add pantheon ssh://codeserver.dev.$PUUID@codeserver.dev.$PUUID.drush.in:2222/~/repository.git
- git push --force pantheon $PSITE

# Create a new Pantheon environment using the above branch.
- drush psite-ecreate $PUUID $PSITE --source=$PSOURCE || true

# Update our drush aliases file.
- drush paliases
- drush cc drush

# We cannot be in a Drupal directory to run aliased drush commands.
- cd $HOME

# When new modules are added to the codebase, updb can sometimes fail (thus
# causing a failed build) because the system table and modules are out of
# sync. We get around this by clearing all caches before attempting anything.
# The "|| true" works around issues where Views and Block conflict during
# cache clears / block rehashes.
- drush @pantheon.$PNAME.$PSITE cc all --strict=0 || true

# Run all available updates as if deploying. For now, append the
# --strict=0 option for Drush 6.x compatibility on Pantheon.
- drush @pantheon.$PNAME.$PSITE updb -y --strict=0

script:

after_script:
# Destroy the Pantheon environment
- drush psite-edelete $PUUID $PSITE -y

# Delete the git branch we created.
- cd $TRAVIS_BUILD_DIR; git push pantheon :$PSITE
